#!/bin/bash

echo "🧪 Testando sistema de temas..."
echo ""
echo "✅ Servidor está rodando em: http://localhost:3001"
echo ""
echo "🔍 Pontos para testar:"
echo "   1. ☀️  Clique no ícone de Sol/Lua no header"
echo "   2. 🌙  Verifique se o fundo muda de claro para escuro"
echo "   3. 📝  Verifique se o texto muda de cor"
echo "   4. 🎨  Verifique se os componentes mudam de cor"
echo "   5. 🔄  Recarregue a página e veja se mantém o tema"
echo "   6. 🌐  Teste também o toggle de idiomas (EN/PT)"
echo ""
echo "🐛 Se não estiver funcionando:"
echo "   • Abra o DevTools (F12)"
echo "   • Vá na aba Console"
echo "   • Verifique se há erros"
echo "   • Vá na aba Elements e veja se <html> tem class 'dark' ou 'light'"
echo ""
echo "💡 Dica: O tema deve mudar INSTANTANEAMENTE ao clicar no botão!"
echo ""
echo "Press Ctrl+C para parar este script e testar"
read -p ""
